/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;


import ec.ups.edu.controlador.ControladorActividad;
import ec.ups.edu.controlador.ControladorEstudiante;
import ec.ups.edu.controlador.ControladorInicioSesion;
import ec.ups.edu.controlador.ControladorProfesor;
import javax.swing.JMenuItem;

/**
 *
 * @author santi
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    ControladorInicioSesion controladorInicioSesion;
    ControladorProfesor controladorProfesor;
    VentanaInicioSesion ventanaIniciarSesion;
    VentanaGestionDocentes ventanaGestionDocente;
    VentanaGestionEstudiantes ventanaGestionEstudiantes;
    ControladorEstudiante controladorEstudiante;
    ControladorActividad controladorActividad;
    
    public VentanaPrincipal() {
        initComponents();
        
        
        
        controladorInicioSesion = controladorInicioSesion.getInstancia();
        controladorEstudiante = controladorEstudiante.getInstancia();
        controladorProfesor = controladorProfesor.getInstancia();
        controladorActividad = new ControladorActividad();
        ventanaIniciarSesion = new VentanaInicioSesion(controladorInicioSesion,this);
        ventanaGestionDocente = new VentanaGestionDocentes(controladorProfesor);
        ventanaGestionEstudiantes = new VentanaGestionEstudiantes(controladorEstudiante, controladorActividad);
        itemGestionDocente.setVisible(false);
        itemVentanaGestionEstudiantes.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemIniciarSesion = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        itemGestionDocente = new javax.swing.JMenuItem();
        itemVentanaGestionEstudiantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        itemIniciarSesion.setMnemonic('o');
        itemIniciarSesion.setText("Inicio Sesion");
        itemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(itemIniciarSesion);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Gestion");

        itemGestionDocente.setMnemonic('t');
        itemGestionDocente.setText("Ventana Gestion Administrador");
        itemGestionDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionDocenteActionPerformed(evt);
            }
        });
        editMenu.add(itemGestionDocente);

        itemVentanaGestionEstudiantes.setMnemonic('t');
        itemVentanaGestionEstudiantes.setText("Ventana Gestion Estudiantes");
        itemVentanaGestionEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentanaGestionEstudiantesActionPerformed(evt);
            }
        });
        editMenu.add(itemVentanaGestionEstudiantes);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void itemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionActionPerformed
        
        desktopPane.add(ventanaIniciarSesion);
        ventanaIniciarSesion.setVisible(true);
        

    }//GEN-LAST:event_itemIniciarSesionActionPerformed

    private void itemGestionDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionDocenteActionPerformed
        
        desktopPane.add(ventanaGestionDocente);
        ventanaGestionDocente.setVisible(true);
        
        
    }//GEN-LAST:event_itemGestionDocenteActionPerformed

    private void itemVentanaGestionEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentanaGestionEstudiantesActionPerformed
        
        desktopPane.add(ventanaGestionEstudiantes);
        ventanaGestionEstudiantes.setVisible(true);
        
    }//GEN-LAST:event_itemVentanaGestionEstudiantesActionPerformed

   public JMenuItem ventanaGestionssDocente(){
        
        return itemGestionDocente;
        
    }
   
   public JMenuItem ventanaGestionEstudiante(){
       
       return itemVentanaGestionEstudiantes;
       
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemGestionDocente;
    private javax.swing.JMenuItem itemIniciarSesion;
    private javax.swing.JMenuItem itemVentanaGestionEstudiantes;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
